import os
import pandas as pd
import numpy as np


class QCACalibrator:
    """
    Convert raw text-prototype similarity scores into QCA set-membership values.

    This module supports two calibration strategies:

    1. Fuzzy-set calibration:
       Raw scores are transformed into membership values between 0 and 1.
       The user provides three anchors:
       - full_in: score at or above which a case is mostly/full in the set
       - crossover: score where membership is maximally ambiguous, usually 0.5
       - full_out: score at or below which a case is mostly/full out of the set

    2. Crisp-set calibration:
       Raw scores are converted into binary values.
       - score >= threshold -> 1
       - score < threshold -> 0
    """

    def __init__(self):
        pass

    def load_score_table(self, score_file_path):
        """
        Load score table generated by text_scoring.py.

        Parameters
        ----------
        score_file_path : str
            Path to score_table.csv.

        Returns
        -------
        pd.DataFrame
            Score table.
        """
        if not os.path.exists(score_file_path):
            raise FileNotFoundError(f"Score file not found: {score_file_path}")

        df = pd.read_csv(score_file_path)

        score_cols = [col for col in df.columns if col.endswith("_score")]
        if not score_cols:
            raise ValueError("No score columns found. Expected columns ending with '_score'.")

        return df

    def fuzzy_calibrate_score(self, score, full_out=0.20, crossover=0.35, full_in=0.50):
        """
        Calibrate one raw score into fuzzy-set membership.

        This implementation uses a transparent piecewise linear function.

        Parameters
        ----------
        score : float
            Raw semantic similarity score.
        full_out : float
            Lower anchor. Scores at or below this value become 0.
        crossover : float
            Crossover anchor. Scores at this value become 0.5.
        full_in : float
            Upper anchor. Scores at or above this value become 1.

        Returns
        -------
        float
            Fuzzy-set membership value between 0 and 1.
        """
        if pd.isna(score):
            return np.nan

        score = float(score)

        if not (full_out < crossover < full_in):
            raise ValueError("Anchors must satisfy: full_out < crossover < full_in")

        if score <= full_out:
            return 0.0
        elif score >= full_in:
            return 1.0
        elif score < crossover:
            return 0.5 * (score - full_out) / (crossover - full_out)
        else:
            return 0.5 + 0.5 * (score - crossover) / (full_in - crossover)

    def crisp_calibrate_score(self, score, threshold=0.35):
        """
        Calibrate one raw score into crisp-set membership.

        Parameters
        ----------
        score : float
            Raw semantic similarity score.
        threshold : float
            Cutoff threshold.

        Returns
        -------
        int
            1 if score >= threshold, otherwise 0.
        """
        if pd.isna(score):
            return np.nan

        return int(float(score) >= threshold)

    def calibrate_dataframe(
        self,
        score_df,
        method="fuzzy",
        full_out=0.20,
        crossover=0.35,
        full_in=0.50,
        threshold=0.35,
        keep_score_columns=True
    ):
        """
        Calibrate all condition score columns in a score table.

        Parameters
        ----------
        score_df : pd.DataFrame
            Score table generated by text_scoring.py.
        method : str
            "fuzzy" or "crisp".
        full_out : float
            Lower anchor for fuzzy calibration.
        crossover : float
            Crossover anchor for fuzzy calibration.
        full_in : float
            Upper anchor for fuzzy calibration.
        threshold : float
            Threshold for crisp calibration.
        keep_score_columns : bool
            Whether to keep raw score columns in the output.

        Returns
        -------
        pd.DataFrame
            Calibrated membership table.
        """
        if method not in ["fuzzy", "crisp"]:
            raise ValueError("method must be either 'fuzzy' or 'crisp'.")

        score_cols = [col for col in score_df.columns if col.endswith("_score")]
        if not score_cols:
            raise ValueError("No score columns found. Expected columns ending with '_score'.")

        calibrated_df = score_df.copy()

        for score_col in score_cols:
            condition_name = score_col.replace("_score", "")

            if method == "fuzzy":
                calibrated_df[condition_name] = calibrated_df[score_col].apply(
                    lambda x: self.fuzzy_calibrate_score(
                        x,
                        full_out=full_out,
                        crossover=crossover,
                        full_in=full_in
                    )
                )
            else:
                calibrated_df[condition_name] = calibrated_df[score_col].apply(
                    lambda x: self.crisp_calibrate_score(
                        x,
                        threshold=threshold
                    )
                )

        if not keep_score_columns:
            calibrated_df = calibrated_df.drop(columns=score_cols)

        return calibrated_df

    def create_qca_ready_dataset(
        self,
        calibrated_df,
        outcome_column="outcome",
        case_id_column="case_id"
    ):
        """
        Create QCA-ready dataset.

        Each row is one case.
        Each calibrated condition is one column.
        The outcome is clearly retained.

        Parameters
        ----------
        calibrated_df : pd.DataFrame
            Calibrated membership table.
        outcome_column : str
            Outcome column name.
        case_id_column : str
            Case ID column name.

        Returns
        -------
        pd.DataFrame
            QCA-ready dataset.
        """
        score_cols = [col for col in calibrated_df.columns if col.endswith("_score")]
        condition_cols = [
            col for col in calibrated_df.columns
            if col not in score_cols
            and col not in [case_id_column, "text", outcome_column]
        ]

        required_cols = []

        if case_id_column in calibrated_df.columns:
            required_cols.append(case_id_column)

        required_cols.extend(condition_cols)

        if outcome_column in calibrated_df.columns:
            required_cols.append(outcome_column)
        else:
            raise ValueError(f"Outcome column '{outcome_column}' not found.")

        qca_df = calibrated_df[required_cols].copy()

        return qca_df

    def save_dataframe(self, df, output_path):
        """
        Save dataframe to CSV.

        Parameters
        ----------
        df : pd.DataFrame
            DataFrame to save.
        output_path : str
            Output path.
        """
        output_dir = os.path.dirname(output_path)

        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        df.to_csv(output_path, index=False, encoding="utf-8-sig")
        print(f"Saved to: {output_path}")


def run_demo():
    """
    Run demo calibration workflow.
    """
    input_file = "outputs/score_table.csv"

    fuzzy_output_file = "outputs/calibrated_membership_table_fuzzy.csv"
    crisp_output_file = "outputs/calibrated_membership_table_crisp.csv"
    qca_ready_output_file = "outputs/qca_ready_dataset.csv"

    calibrator = QCACalibrator()

    score_df = calibrator.load_score_table(input_file)

    print("\nRaw score table preview:")
    print(score_df.head())

    # Fuzzy-set calibration
    fuzzy_df = calibrator.calibrate_dataframe(
        score_df=score_df,
        method="fuzzy",
        full_out=0.15,
        crossover=0.35,
        full_in=0.45,
        keep_score_columns=True
    )

    print("\nFuzzy calibrated membership table preview:")
    print(fuzzy_df.head())

    calibrator.save_dataframe(fuzzy_df, fuzzy_output_file)

    # Crisp-set calibration
    crisp_df = calibrator.calibrate_dataframe(
        score_df=score_df,
        method="crisp",
        threshold=0.30,
        keep_score_columns=True
    )

    print("\nCrisp calibrated membership table preview:")
    print(crisp_df.head())

    calibrator.save_dataframe(crisp_df, crisp_output_file)

    # For the next QCA step, we use crisp-set conditions as the default demo version.
    # Crisp-set values are easier for building a basic truth table.
    qca_ready_df = calibrator.create_qca_ready_dataset(
        calibrated_df=crisp_df,
        outcome_column="outcome",
        case_id_column="case_id"
    )

    print("\nQCA-ready dataset preview:")
    print(qca_ready_df.head())

    calibrator.save_dataframe(qca_ready_df, qca_ready_output_file)


if __name__ == "__main__":
    run_demo()